name: 'Build composition repo'

on:
  workflow_dispatch: # Allow triggering manually

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      project: ${{ ${github.event.repository.name//ose_composition_} }}

    steps:
      - run: |
          echo "$project"
