name: 'Build composition repo'

on:
  workflow_dispatch: # Allow triggering manually

jobs:
  determine_project:
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.determine.outputs.project }}
    steps:
      - name: Extract project-name from repo-name
        id: determine
        run: |
          echo "project=${GITHUB_REPO##ose_composition_}" >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: determine_project
    env:
      PROJECT: ${{ needs.determine_project.outputs.project }}
    steps:
      - name: "Build"
        run: |
          echo "building project $PROJECT soon..."
