name: 'Build composition repo'

on:
  workflow_dispatch: # Allow triggering manually

jobs:
  determine_project:
    runs-on: ubuntu-latest
    outputs:
      project: ${{ steps.determine.outputs.project }}
    steps:
      - name: Extract project-name from repo-name
        id: determine
        run: |
          echo "project=${GITHUB_REPOSITORY##hitobito/ose_composition_}" >> "$GITHUB_OUTPUT"

  build:
    uses: hitobito/hitobito/.github/workflows/build-image.yml@new-dockerfile
    needs: determine_project
    with:
      composition: ${{ github.event.repository.name }}
      source_ref: devel
      project: ${{ needs.determine_project.outputs.project }}
      # version: sssoooooonnn...
    secrets: inherit
